---
language: python
python:
  - "2.7"
  - "2.6"
branches:
  only:
    - master
before-script: pip install python-coveralls nosexcover
script: nosetests --with-xcoverage --xcoverage-file=.coverage
after_success: coveralls