---
language: python
python:
  - "2.7"
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: nosetests --with-coverage --cover-package=cellplayground
after_success: coveralls